services:
    db:
        image: postgres:15.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: looper
        volumes:
            - postgres_data_spotify_looper:/var/lib/postgresql/data

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - db
        ports:
            - "4001:4001"
        environment:
            DATABASE_URL: postgres://postgres:password@db:5432/looper

volumes:
    postgres_data_spotify_looper:
