services:
    postgres-looper:
        image: postgres:15.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: looper
        volumes:
            - postgres_data_spotify_looper:/var/lib/postgresql/data
        # ports:
        #     - "5432:5432"
        networks:
            - spotify-looper-network

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - postgres-looper
        ports:
            - "4001:4001"
        environment:
            DATABASE_URL: postgres://postgres:password@postgres-looper:5432/looper
        networks:
            - spotify-looper-network

volumes:
    postgres_data_spotify_looper:

networks:
    spotify-looper-network:
        driver: bridge
